### ISSUE TITLE
Create Trip-notes

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/takeatrip#18]
## Value statement
As a **user who likes to travel**
I want to add notes for my trip
so that **I can organize ideas, sightseeing, hotel-links** for example.

## Description
<img src="https://user-images.githubusercontent.com/59579694/76348946-62b36180-6309-11ea-99b5-b395d4d429a2.jpg" width="200" />

## Acceptance criteria
- [x] click on "Notiz hinzufügen" open a form with textinput for title, textarea and save-button
- [x] the textarea includes an editor-toolbar with bold, italic, ul/ol list
- [x] click on save-button saves the note 
- [x] The user ends up in detail-page/notelist after submit
- [x] The new note is added at the top
- [x] The form is found at the path "/create-note"
- [x] There is a button to cancel creation of new note / go back to detail-page

## Tasks
- [x]  Register API-key at TinyMCE
- [x]  Create new page to Router
- [x]  Create new component TextEditor
- [x]  Implement Tiny mce editor
- [x]  Configure Tiny mce editor
- [x]  build a form with input for title and editor for content
- [x]  Implement backlink 
- [x]  Styling 
- [x]  Testing UX on browser and smartphone

## Size
XL
