### ISSUE TITLE
Feature Bookmark

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/takeatrip#30]
## Value statement
As a **user who likes to travel**.
I need to **bookmark** some of my trips,
that helps me to find my favorite trips.

## Description
![gesellenstueck](https://user-images.githubusercontent.com/59579694/77556649-1182a080-6eb9-11ea-9db2-b1b08a6dd56a.jpg)

## Acceptance criteria
- [x] A click on the bookmark-icon toggle the color
- [x] A click on the list-link in the navigation filters the trips to the bookmark-items

## Tasks
- [x] Include bookmark-Icon
- [x] Add toggle-function
- [x] Filter triplist to bookmark items
- [x] Add new component Navigation to the app
- [x] Styling 
- [x] Testing UX on browser and smartphone

## Size
L
