### ISSUE TITLE
delete notes

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/takeatrip#31]
## Value statement
As a **user who likes to travel**.
I need to **bookmark** some of my trips,
that helps me to find my favorite trips.

## Description
![gesellenstueck](https://user-images.githubusercontent.com/59579694/77556649-1182a080-6eb9-11ea-9db2-b1b08a6dd56a.jpg)

## Acceptance criteria
- [ ] A click on the bookmark-icon toggle the color
- [ ] A click on the list-link in the navigation filters the trips to the bookmark-items

## Tasks
- [ ] Include bookmark-Icon
- [ ] Add toggle-function
- [ ] Filter triplist to bookmark items
- [ ] Add new component Navigation to the app
- [ ] Styling 
- [ ] Testing UX on browser and smartphone

## Size
L
