### ISSUE TITLE
edit notes

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/takeatrip#32]
## Value statement
As a **user who likes to travel**.
I need to **edit** my notes on a trip,
that helps me to organize my trips.

## Description
/

## Acceptance criteria
- [ ] A click on the note-item shows the full text. At the end there is a edit-button.
- [ ] A click on the edit-button open the note-editor with the current full content, so i can edit the text.

## Tasks
- [ ] Add edit-button to the note-item
- [ ] Add edit-function
- [ ] Testing UX on browser and smartphone

## Size
S
