### ISSUE TITLE
Edit trips

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/takeatrip#33]
## Value statement
As a **user who likes to travel**.
I need to **edit** my trips,
so I can rename the title, date and country of the trip

## Description
/

## Acceptance criteria
- [ ] The edit-button is located at the trip-detail-page
- [ ] The edit-button is located next to the delete-button
- [ ] Click on the edit-button opens the create-trips-form with d

## Tasks
- [ ] Add edit-button to the note-item
- [ ] Add edit-function
- [ ] Testing UX on browser and smartphone

## Size
S
