### ISSUE TITLE
Opitional input of the country

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/takeatrip#34]
## Value statement
As a **user who likes to travel**.
I need to **add a country-entry** to my trip
that helps me to organize my trips.

## Description
/

## Acceptance criteria
- [ ] The create-trip-form includes a select-input "country"
- [ ] I can select a country from a list of countries

## Tasks
- [ ] Add select-input 
- [ ] Includes a list of countries / recherche
- [ ] Styling
- [ ] Testing UX on browser and smartphone

## Size
S
